/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Catalogue: typeof import('./../components/layout/Catalogue.vue')['default']
    FooterView: typeof import('./../components/layout/FooterView.vue')['default']
    HeaderView: typeof import('./../components/layout/HeaderView.vue')['default']
    ICustomBilibili: typeof import('~icons/custom/bilibili')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    Plum: typeof import('./../components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubNav: typeof import('./../components/layout/SubNav.vue')['default']
    ToggleLocale: typeof import('./../components/ToggleLocale.vue')['default']
    ToggleTheme: typeof import('./../components/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./../components/WrapperPost.vue')['default']
  }
}
